version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: neuromove-mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_local:/var/lib/mysql

  redis:
    image: redis:7
    container_name: neuromove-redis-local
    restart: always
    ports:
      - "6380:6379"

volumes:
  mysql_data_local: