spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3307/emg_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

security:
  api-key: YOUR_API_KEY